version: '3.8'

services:
  ecommerceapi:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    build:
      context: .
      dockerfile: EcommerceAPI/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ecommerceDb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: